### PR TITLE
dotnet core compatibility

### PR DESCRIPTION
**Pull request by sandorfr**
issue #116

### CODE REVIEW

**Comment by sandorfr** [comment]
friendly ping @rexm  :)

**Comment by rexm** [comment]
2 items:

1) Have you tested importing this nuget package into projects that target 4.5.x and 4.6.x to ensure there's no issues across any compatible framework?

2) Unfortunately you got caught in a stream of several other PRs, so there's some conflicts that need a little love.

Thanks

**Comment by sandorfr** [comment]
@rexm  you where right, netstandard/451 was conflicting with the portable library target. 
Luckily this is not needed since a .net core project targetting net451 can deal with classic portable library.

Regarding other PRs, that's life and this is for the greater good :d so I updated my branch.

I also have another branch where I migrated from nunit to mstest to run the tests against .net core target https://github.com/sandorfr/Handlebars.Net/tree/feature/dotnet-core-rc2-mstest . I found that 3 test are broken. I on it.

**Comment by sandorfr** [comment]
@rexm tests are now all green (except for caspar which relies on library which does not support .net core yet)

**Comment by rexm** [comment]
I'm looking at expanding the build matrix to include core.

**Comment by sandorfr** [comment]
just added nunit unit test project thanks to latest alpha of nunit test runner and nunitlite

**Comment by trongdong** [comment]
What happens with this? Is it ready to merge?

**Comment by sandorfr** [comment]
As far as I'm concerned it is ready to merge but If there is anything wrong I'm ready to fix it. 
In the meantime if you need to work with this now you can use the package I published here : https://www.nuget.org/packages/Handlebars.NetStandard/1.0.0-dotnet-core-rc2-0001

**Comment by rexm** [comment]
I'm going to merge this, but it may still take a few days before it gets to Nuget.

**Comment by sandorfr** [comment]
@rexm sounds fair, people can use the one I published until then.

**Comment by rexm** [comment]
What target(s) did you use to build the dotnet core version for packaging?

**Comment by sandorfr** [comment]
Do you have the RC2 visual studio tools installed?

The package I published is issue using `dotnet pack -c Release` (since it is only intended for people targeting .net core). 

To package using your nuspec I was building the regular sln then building the .net core project using `dotnet build -c Release` in the netstandard project directory. Then you a basic `nuget pack` did the job. 

I'll make new PR in a few days with .net core RTM.

**Comment by rexm** [comment]
I get `error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute` when trying to build with .net core. I haven't spent any time digging in yet.

**Comment by sandorfr** [comment]
@rexm never got that error, I upgraded to RTM ( PR #140 ). Let me know if it's working better. (You'll need visual studio update 3 and .net core RTM)

**Comment by rexm** [comment]
Same issue with RTM. Haven't had time to do a deep dive; quick google search didn't reveal much.

**Pull request merged**
