### PR TITLE
Added support for Raw Blocks / Quad Mustache syntax

### LINKED ISSUE #179: How can I achieve a raw block helper?
I'm trying to compile a handlebars template server side that has a handlebars template in it that I want to compile clients side. The Handlebars documentation has this:

[http://handlebarsjs.com/block_helpers.html](http://handlebarsjs.com/block_helpers.html)
Raw Blocks

Raw blocks are available for templates needing to handle unprocessed mustache blocks.
```
{{{{raw-helper}}}}
  {{bar}}
{{{{/raw-helper}}}}
```
will execute the helper raw-helper without interpreting the content.
```
Handlebars.registerHelper('raw-helper', function(options) {
  return options.fn();
});
```
will render

```
{{bar}}
```

However, my attempt using Handlebars.Net still seems to be compiling the inner block. 
```
{{{#raw-helper}}}
      {{myhelper key}}
{{{/raw-helper}}}
```
```
Handlebars.RegisterHelper("raw-helper", (writer, options, context, parameters) =>{
                options.Template(writer, null);
            });
```
And so I'm getting an error that the helper myhelper is undefined, which is true for this pass since myhelper is defined client side.

If I use {{{{raw-helper}}}} I get the error: "Reached unparseable token in expression: {raw-helper}}}}"

Note: I'm using Handlebars.Net version 1.7.1, I'd prefer not to update yet, but will if it will help get me to where I want to be.

### PR DESCRIPTION
**Pull request by vzwick**
Fixes #179, feedback is much appreciated

### CODE REVIEW

**Comment by vzwick** [comment]
Sorry about pushing more commits - I had blatantly overlooked a few edge cases around reassembling the body after tokenization.

**Comment by rexm** [comment]
Need to check why CI isn’t running on this PR

**Comment by vzwick** [comment]
[It actually is](https://travis-ci.org/rexm/Handlebars.Net/builds/506457319), just not updating the status on GitHub.

**Comment by rexm** [comment]
Do you need to do any more edge case testing?

**Comment by vzwick** [comment]
I don't think so - at least I didn't stumble upon any other readily apparent issues.

**Pull request merged**
