### PR TITLE
Set TFM to minimum of net452

### PR DESCRIPTION
**Pull request by jchannon**
The minimum full fwk now supported is net452

### CODE REVIEW

**Comment by rexm** [comment]
What was the driver for this change?

**Comment by jchannon** [comment]
net452 is the oldest fwk version that is now supported

**Comment by jchannon** [comment]
https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

**Comment by rexm** [comment]
Ah, forgot about that. Thanks

**Pull request merged**
