### PR TITLE
Signed assembly.

### PR DESCRIPTION
**Pull request by tonysneed**
To create strongly named assembly.

### CODE REVIEW

**Comment by tonysneed** [comment]
@rexm, I forked your repo in order to sign the assembly and publish it to NuGet.  But if you like you can simply merge this PR, which will alleviate the need for my fork.

**Comment by rexm** [comment]
This PR is not mergeable

**Comment by rexm** [comment]
Released 1.9.4 with a signed assembly.

**Comment by tonysneed** [comment]
@rexm Just add this to the csproj file for it to build on Travis:
```xml
<PublicSign Condition=" '$(OS)' != 'Windows_NT' ">true</PublicSign>
```

**Comment by tonysneed** [comment]
Resolves issue #193.

**Pull request closed without merging**
