### PR TITLE
Add support for special named @partial-block partials

### PR DESCRIPTION
**Pull request by huysentruitw**

### CODE REVIEW

**Comment by huysentruitw** [comment]
@rexm do you have any idea what's wrong with the build? I can build and run the unit-tests locally without any problem.

**Comment by rexm** [comment]
Not sure, it started yesterday. Haven't had time to dig into the exact error yet.

**Comment by rexm** [comment]
Looks like it was an internal issue with Travis... working now.

**Comment by huysentruitw** [comment]
Ok, great. Let me know what you think about the PR.

**Comment by huysentruitw** [comment]
@rexm is their any chance this fix can get into the Handlebars.Net library? (We would love to keep using the upstream library).

**Comment by huysentruitw** [comment]
**_&lt;keep-alive /&gt;_** 😄

**Comment by huysentruitw** [comment]
@rexm any chance to get this PR in this code-base or do we need to search for a different solution? Don't want to force anything here, but we need to know how to proceed with this issue. Thank you.

**Pull request merged**
