### PR TITLE
Fix null literal binding

### PR DESCRIPTION
**Pull request by mohd-akram**

### CODE REVIEW

**Comment by mohd-akram** [comment]
Since C# has no concept of undefined, I figured it would be the same as null.

**Comment by rexm** [comment]
That may create some more subtle bugs down the line. Suggest we introduce an Undefined type with an equality operator overload for comparisons to null, and add a check for it in the Truthy/Falsy helpers.

**Comment by mohd-akram** [comment]
Yeah, true. I've changed the PR to just check for `null` which is more important. Right now `undefined` results in `UndefinedBindingResult` which is pretty close and with #244 it's easy to check.

**Comment by rexm** [comment]
Thanks! Will look at releasing this weekend.

**Pull request merged**
