### PR TITLE
Added ClearRegisteredTemplates method. Use it while in development to se...

### PR DESCRIPTION
**Pull request by nkwinder**
Added a method, for clearing all the registered templates. Seems to be working... as expected. Any ideas?

### CODE REVIEW

**Comment by rexm** [comment]
Seems like that is a more consistent approach.

**Comment by nkwinder** [comment]
New commits revert the initial changes and make the partials overwrite each time they are registered. 

So now in my app, in production, the registerTemplate will be called only in Application Start, but now i have also the option to call registerTemplate in Begin Request, (if in development mode), and changes will be shown without an app restart.

Seems legit? 

p.s What about renaming the function to registerPartial ?

**Comment by nkwinder** [comment]
Any update on this one? Am i missing something?

**Comment by rexm** [comment]
1.1.2 pushed to NuGet

**Pull request merged**
