### PR TITLE
Suggested resolution for issue #214

### PR DESCRIPTION
**Pull request by lot224**
Updated line 64 of source/Handlebars/Compiler/HandlebarsCompiler.cs

This will allow the context to be passed into the layout partial.

### CODE REVIEW

**Comment by rexm** [comment]
Thanks. Can you add unit tests for this please?

**Comment by rexm** [comment]
Aiming to get this out to NuGet tonight.

**Comment by lot224** [comment]
ETA on this NuGet release?  I'd rather use your release than mine.

**Comment by Magentaize** [comment]
@rexm Could you upload a new version on NuGet with this fix? Thanks!

**Pull request merged**
