### PR TITLE
Add support for JObject's to #if

### PR DESCRIPTION
**Pull request by ejsmith**

### CODE REVIEW

**Comment by ejsmith** [comment]
Let me know what you think about this solution. Obviously, we don't want to add a reference to JSON.NET, so I am just checking for the type name and having to use a little reflection.

**Comment by rexm** [comment]
This seems more problematic than taking the binary dependency. Is this a problem you can address in the app with an adapter pattern?

**Comment by ejsmith** [comment]
I definitely think the library should support using JObject as the data source, but I didn't really think it was worth it to take on the dependency directly. If you would rather take a dependency on JSON.NET then that is fine.

Not sure what you mean about the adapter pattern. Do you mean that I should try and adapt my source object into a different type that would work better with your lib?

**Comment by rexm** [comment]
Yes, JSON.NET has a number of conventions for producing object graphs that are convertible to BCL types, discussed as recently as yesterday - https://github.com/rexm/Handlebars.Net/issues/88

**Comment by ejsmith** [comment]
I just looked through pull #82 and I think this could be implemented as a IMemberAccessor. We would just need to make sure that end users can plug in custom member accessors through a configuration setting. Then we could just add a simple JObject member accessor that uses JSON.NET directly.

**Comment by rexm** [comment]
PR #82 is closed, but that idea seems like a reasonable path forward.

**Pull request closed without merging**
