### PR TITLE
Update to support .NetStandard 1.3

### PR DESCRIPTION
**Pull request by StefH**
1. Add support for .NetStandard 1.3
2. Add .NETPortable,Version=v4.0,Profile=Profile24

The NetStandard project contains now 3 frameworks:
- net45
- netstandard1.3
- portable40-net45+sl5

You can use the `_build nuget.cmd` file to create a NuGet whihc you can directly commit to NuGet.org

### CODE REVIEW

**Comment by axelheer** [comment]
Yeah, when will this get released?

**Comment by rexm** [comment]
I'll try to get it out sometime today.

**Comment by axelheer** [comment]
*ping*

**Comment by sbebrys** [comment]
Hi, when You release new version? Net standard would be great feature.

**Pull request merged**
