### PR TITLE
Build def update for #63 from @leniency

### PR DESCRIPTION
**Pull request by rexm**

### CODE REVIEW

**Comment by rexm** [comment]
I've pushed a pre-release v1.5.0-beta to NuGet. @leniency @dejx - this has impacts to how we handle PCL, can you please test that version and give feedback here?

**Comment by rexm** [comment]
OK, I backed out this changeset. Feel free to re-submit when you're ready @leniency. Thanks @dejx!

**Comment by dejx** [comment]
Was this properly merged?
i'm looking at the nuspec file https://github.com/rexm/Handlebars.Net/blob/master/Handlebars.Net.nuspec

There is only one file being added into nuget package, while diff on this had two, this is related to https://github.com/rexm/Handlebars.Net/issues/78 and it would solve this issue

**Comment by rexm** [comment]
I'll check this weekend.

**Pull request merged**
