### PR TITLE
Improve build

### PR DESCRIPTION
**Pull request by axelheer**
- unify the .NET Framework and .NET Standard builds using the new "Microsoft.NET.Sdk" build system 
- build NuGet package directly on build using the new "Microsoft.NET.Sdk" build system
- requires Visual Studio 2017 or .NET CLI 1.0 because of the new stuff...

~~*Note:* there seems to be no .NET Core support by NUnit yet; thus, the tests do not run using the .NET Core CLI (any idea anyone? I don't usually use NUnit...)~~

~~*Note:* I had to add some code to the Caspar tests to fix the current working directory... (?)~~

### CODE REVIEW

**Comment by axelheer** [comment]
Ah, I just noticed, that you're using Travis and xbuild, which cannot handle that.

**Comment by StefH** [comment]
I think that AppVeyor does not have support for VS2017 yet.

**Comment by axelheer** [comment]
They have an image for it at least:

image

Or, we port the tests to xunit / mstest; then we could just use the CLI [like that](https://github.com/axelheer/nein-linq/blob/master/appveyor.yml).

**Comment by axelheer** [comment]
Yeah, switching to xUnit is no problem. Let me know, if I should include this commit.

**Comment by StefH** [comment]
NUnit works for `netcoreapp1.0` , see
https://github.com/StefH/SimMetrics.Net/blob/42dddeb4ca3661bbe59e851399c0a90c5e1ff7f0/tests/SimMetrics.Net.Tests/project.json

However, I had troubles running codecoverage and so on, so I switched back to net452 for running the tests.

**Comment by axelheer** [comment]
@StefH `dotnet-test-nunit` is for project.json, not msbuild?

**Comment by axelheer** [comment]
@rexm switching to AppVeyor works fine. I've added an `appveyor.yml` and tested it using my fork. [Have a look](https://ci.appveyor.com/project/AxelHeer/handlebars). You can even download the NuGet Package there (under artifacts).

**Comment by rexm** [comment]
Very cool. I'll take a look this evening!

**Comment by StefH** [comment]
@axelheer Do you also know if *coverage* / *coveralls* does work fine?

**Comment by axelheer** [comment]
@StefH using OpenCover with the .NET CLI works fine for both, .NET Core and .NET Framework. I can add that to the`appveyor.yml` (but today I'm on the road). 

/axel

**Comment by StefH** [comment]
@axelheer Thanks for your help.
Currently I'm struggling to get [my vs2017 project (SimMetrics.Net)](https://github.com/StefH/SimMetrics.Net/tree/_vs2017) to build in AppVeyor or Travis.

However no success yet.

**Comment by axelheer** [comment]
The AppVeyor build now includes code coverage analysis based on OpenCover and ReportGenerator. I've included the results within the build artifacts, so they're available for download. Of course, it's possible to deploy / push them somewhere if needed.

**Comment by StefH** [comment]
@axelheer 
Yes I want to build my project in AppVeyor/Travis for the new NETStandard (using `dotnet cli`) but also legacy frameworks (e.g. NET20 or NET40). On my local system, all can be build using VS2017, but in AppVeyor/Travis this fails.

Maybe I need to install also `Mono` on the build-system (besides `dotnet` ?)

**Comment by rexm** [comment]
Will push this evening

**Comment by StefH** [comment]
Thanks for your work. I was able to get AppVeyor + VS2017 project building and tested.
See https://github.com/StefH/SimMetrics.Net/tree/_vs2017

**Pull request merged**
