### PR TITLE
Added Netstandard2.0

### PR DESCRIPTION
**Pull request by uffebjorklund**
I am on a Mac so I only compiled for netstandard, did not change any code so net452 etc should be fine. Please note that I changed version (in Handlebars.csproj) and added some lines in travis.yml and appveyor.yml that you might wanna discard.

Regards, Uffe

### CODE REVIEW

**Comment by uffebjorklund** [comment]
My guess is that the build failed since it is using net sdk 1.0.1 and not 2.0.
Found a fix here: https://codeblog.jonskeet.uk/2017/08/15/using-net-core-2-0-sdk-on-travis/ by J Skeet since you probably want net core 1.0 support as well.

**Comment by rexm** [comment]
Ok, waiting for green

**Comment by uffebjorklund** [comment]
@rexm is it ok? If it is all good, can you release a new version to nuget after accepting?

**Comment by rexm** [comment]
Will aim to get it out this weekend.

**Comment by CrosserTechnologies** [comment]
@rexm do you have a estimate for releasing a new version with support for netstandard2.0 to nuget?

**Pull request merged**
